name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
    paths:
      - "supabase/migrations/develop/*.sql" # Monitora alterações nos arquivos .sql
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN_DEVELOP }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integrações do Github (ex.: comentários em PR)
          action: "upload"
          app_location: "/src" # Caminho do código-fonte do app
          api_location: "" # Caminho do código-fonte da API - opcional
          output_location: "." # Diretório de conteúdo compilado do app - opcional
          skip_app_build: true

  update_supabase_job:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    name: Update Supabase Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Supabase CLI
        run: |
          echo "Baixando Supabase CLI..."
          curl -sL https://github.com/supabase/cli/releases/download/v1.63.3/supabase-linux-amd64 -o supabase-cli
          if [ $? -ne 0 ]; then
            echo "Erro ao baixar o Supabase CLI."
            exit 1
          fi
          chmod +x supabase-cli
          sudo mv supabase-cli /usr/local/bin/supabase
          supabase --version

      - name: Apply Migrations with Supabase CLI
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Aplicando migrações..."
          supabase db push --schema-dir supabase/migrations/develop

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN_DEVELOP }}
          action: "close"
