name: CI/CD with Supabase Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    - cron: '25 23 * * *' 

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.action != 'closed') ||
        github.event_name == 'schedule'
    runs-on: ubuntu-latest
    name: Build, Deploy, and Update Supabase Database
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Set up the database connection string from secrets
      - name: Set Environment Variables
        run: echo "GCOCONSTR=${{ secrets.SUPABASE_DB_URL_MAIN }}" >> $GITHUB_ENV

      # Validate the database connection string secret
      - name: Validate Database Connection Secret
        run: |
          if [ -z "$GCOCONSTR" ]; then
            echo "Database connection string is missing! Ensure SUPABASE_DB_URL_MAIN is set.";
            exit 1;
          fi

      # Run migrations
      - name: Apply Supabase Migrations
        run: |
          PGPASSWORD=$(echo $GCOCONSTR | sed -E 's|.*://.*:(.*)@.*|\1|')
          DB_HOST=$(echo $GCOCONSTR | sed -E 's|.*://.*@([^:]*):.*|\1|')
          DB_PORT=$(echo $GCOCONSTR | sed -E 's|.*://.*:.*@.*:([0-9]*)/.*|\1|')
          DB_NAME=$(echo $GCOCONSTR | sed -E 's|.*/([^/]*)$|\1|')
          DB_USER=$(echo $GCOCONSTR | sed -E 's|.*://([^:]*):.*@.*|\1|')

          echo "Connecting to $DB_HOST:$DB_PORT/$DB_NAME as $DB_USER"

          # Apply migrations if any files exist
          if [ "$(ls supabase/migrations/main/*.sql 2>/dev/null)" ]; then
            for file in supabase/migrations/main/*.sql; do
              echo "Applying migration: $file"
              PGPASSWORD=$PGPASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f $file || {
                echo "Failed to apply migration: $file"; exit 1;
              }
            done
          else
            echo "No migration files found in supabase/migrations/main"
          fi
        shell: bash

      # Build and deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_MUSHROOM_03989E210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src"
          api_location: ""
          output_location: "."

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_MUSHROOM_03989E210 }}
          action: "close"
