name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
    paths:
      - "supabase/migrations/develop/*.sql" # Monitora alterações nos arquivos .sql
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN_DEVELOP }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integrações do Github (ex.: comentários em PR)
          action: "upload"
          app_location: "/src" # Caminho do código-fonte do app
          api_location: "" # Caminho do código-fonte da API - opcional
          output_location: "." # Diretório de conteúdo compilado do app - opcional
          skip_app_build: true

  update_supabase_job:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    name: Update Supabase Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Supabase CLI
        run: |
          echo "Baixando Supabase CLI..."
          curl -sL https://github.com/supabase/cli/releases/download/v1.226.3/supabase_linux_amd64.tar.gz -o supabase-cli.tar.gz
          if [ $? -ne 0 ]; then
            echo "Erro ao baixar o Supabase CLI."
            exit 1
          fi

          # Verifica se o arquivo tar foi baixado corretamente
          file supabase-cli.tar.gz
          if [ $? -ne 0 ]; then
            echo "O arquivo baixado não é um tarball válido."
            exit 1
          fi

          # Listar o conteúdo do tarball para verificar os arquivos
          echo "Conteúdo do tarball:"
          tar -tzf supabase-cli.tar.gz

          # Cria um diretório temporário para extrair o arquivo
          mkdir -p /tmp/supabase

          # Extrai o tarball para o diretório temporário
          tar -xzf supabase-cli.tar.gz -C /tmp/supabase

          # Verifica se o arquivo binário existe no diretório extraído
          if [ ! -f "/tmp/supabase/supabase-linux-amd64" ]; then
            echo "Binário do Supabase não encontrado após a extração."
            exit 1
          fi

          # Remover o binário existente, se já houver um
          sudo rm -f /usr/local/bin/supabase

          # Mover o binário extraído para o diretório correto
          sudo mv /tmp/supabase/supabase-linux-amd64 /usr/local/bin/supabase

          # Verificar a versão do Supabase CLI
          supabase --version

      - name: Apply Migrations with Supabase CLI
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Aplicando migrações..."
          supabase db push --schema-dir supabase/migrations/develop

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN_DEVELOP }}
          action: "close"
